# Generated by Django 2.2 on 2020-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200525_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=1020),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('OP', 'Abierto'), ('PE', 'Pendiente'), ('IP', 'En proceso'), ('RE', 'Resuelto'), ('CL', 'Cerrado')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
